export interface TabItem {
  id: string;
  label: string;
  iconName: "LayoutDashboard" | "MessageSquare" | "Package" | "ShoppingCart" | "Users" | "Megaphone" | "Zap" | "Settings" | "Calendar" | "Clock" | "Sliders" | "ShieldCheck" | "User" | "FileText" | "BookOpen" | "Utensils";
}

export interface CategoryConfig {
  id: string;
  label: string;
  emoji: string;
  themeColor: string; // Tailwind color class
  textColor: string; // Tailwind text color
  glassTheme: string; // CSS color
  catalogLabel: string; // Products, Menu, Services, Courses, Produce, etc.
  ordersLabel: string; // Orders, Bookings, Enrollments, Appointments, etc.
  customersLabel: string; // Customers, Patients, Clients, Students, Guests, etc.
  heroTitle: string;
  heroSubtitle: string;
  onboarding: string[];
  tabs: TabItem[];
}

export const CATEGORIES_CONFIG: Record<string, CategoryConfig> = {
  retail: {
    id: "retail",
    label: "Retail & E-commerce",
    emoji: "🛍️",
    themeColor: "emerald",
    textColor: "text-emerald-400",
    glassTheme: "rgba(16, 185, 129, 0.15)",
    catalogLabel: "Products",
    ordersLabel: "Orders",
    customersLabel: "Customers",
    heroTitle: "Retail Storefront Hub",
    heroSubtitle: "Manage item listings, control inventory alerts, and configure instant checkout cart rules.",
    onboarding: ["Connect WhatsApp", "Upload Products", "Configure Shipping", "Accept Orders"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Live Chats", iconName: "MessageSquare" },
      { id: "catalog", label: "Products Catalog", iconName: "Package" },
      { id: "inventory", label: "Inventory Control", iconName: "Sliders" },
      { id: "orders", label: "Orders Board", iconName: "ShoppingCart" },
      { id: "customers", label: "Customers CRM", iconName: "Users" },
      { id: "campaigns", label: "Broadcasts", iconName: "Megaphone" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  restaurant: {
    id: "restaurant",
    label: "Restaurant",
    emoji: "🍕",
    themeColor: "orange",
    textColor: "text-orange-400",
    glassTheme: "rgba(249, 115, 22, 0.15)",
    catalogLabel: "Menu Items",
    ordersLabel: "Food Orders",
    customersLabel: "Dine-in Guests",
    heroTitle: "Restaurant Command Center",
    heroSubtitle: "Track active table bookings, monitor live kitchen prep tickets, and sync delivery status.",
    onboarding: ["Connect WhatsApp", "Add Menu Items", "Configure Delivery Radius", "Business Hours"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Guest Messages", iconName: "MessageSquare" },
      { id: "tables", label: "Table Bookings", iconName: "Calendar" },
      { id: "catalog", label: "Menu Designer", iconName: "Utensils" },
      { id: "kitchen", label: "Kitchen Queue", iconName: "Clock" },
      { id: "orders", label: "Live Orders", iconName: "ShoppingCart" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  bakery: {
    id: "bakery",
    label: "Bakery",
    emoji: "🧁",
    themeColor: "amber",
    textColor: "text-amber-400",
    glassTheme: "rgba(245, 158, 11, 0.15)",
    catalogLabel: "Pastries & Cakes",
    ordersLabel: "Custom Orders",
    customersLabel: "Patrons",
    heroTitle: "Bakeshop Operations",
    heroSubtitle: "Plan cake booking schedules, track baking oven queues, and coordinate fresh supply inventories.",
    onboarding: ["Connect WhatsApp", "Upload Bakery Menu", "Configure Delivery", "Baking Schedule"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Order Chats", iconName: "MessageSquare" },
      { id: "catalog", label: "Pastry Menu", iconName: "Package" },
      { id: "kitchen", label: "Baking Queue", iconName: "Clock" },
      { id: "ingredients", label: "Ingredients Stock", iconName: "Sliders" },
      { id: "orders", label: "Cake Orders", iconName: "ShoppingCart" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  grocery: {
    id: "grocery",
    label: "Grocery Store",
    emoji: "🥦",
    themeColor: "lime",
    textColor: "text-lime-400",
    glassTheme: "rgba(132, 204, 22, 0.15)",
    catalogLabel: "Produce & Goods",
    ordersLabel: "Grocery Orders",
    customersLabel: "Store Shoppers",
    heroTitle: "Supermarket Dispatch Desk",
    heroSubtitle: "Manage bulk fresh produce weights, track inventory shelves, and assign local delivery riders.",
    onboarding: ["Connect WhatsApp", "Import Produce List", "Define Delivery Slots", "Add Drivers"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Shopper Chats", iconName: "MessageSquare" },
      { id: "catalog", label: "Produce Catalog", iconName: "Package" },
      { id: "inventory", label: "Shelf Stock", iconName: "Sliders" },
      { id: "orders", label: "Grocery Orders", iconName: "ShoppingCart" },
      { id: "drivers", label: "Delivery Fleet", iconName: "Users" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  electronics: {
    id: "electronics",
    label: "Electronics Store",
    emoji: "💻",
    themeColor: "cyan",
    textColor: "text-cyan-400",
    glassTheme: "rgba(6, 182, 212, 0.15)",
    catalogLabel: "Hardware Units",
    ordersLabel: "Tech Sales",
    customersLabel: "Buyers",
    heroTitle: "Tech Distribution Operating System",
    heroSubtitle: "Track hardware serial serials, manage active repair tickets, and maintain AMC contracts.",
    onboarding: ["Connect WhatsApp", "Import Device SKUs", "Configure AMC Policies", "Technician Accounts"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Support Chats", iconName: "MessageSquare" },
      { id: "catalog", label: "Devices Inventory", iconName: "Package" },
      { id: "warranty", label: "Warranty Tracker", iconName: "ShieldCheck" },
      { id: "repairs", label: "Repairs Deck", iconName: "Sliders" },
      { id: "orders", label: "Sales Orders", iconName: "ShoppingCart" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  hospital: {
    id: "hospital",
    label: "Hospital & Clinics",
    emoji: "🏥",
    themeColor: "rose",
    textColor: "text-rose-400",
    glassTheme: "rgba(244, 63, 94, 0.15)",
    catalogLabel: "Prescriptions",
    ordersLabel: "Appointments",
    customersLabel: "Patients",
    heroTitle: "Clinical Practice Manager",
    heroSubtitle: "Register doctors, open medical appointment slots, and dispatch verified PDF health reports.",
    onboarding: ["Connect WhatsApp", "Add Doctor Profiles", "Setup Clinic Slots", "Report Formats"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Patient Chats", iconName: "MessageSquare" },
      { id: "doctors", label: "Doctors Panel", iconName: "User" },
      { id: "orders", label: "Appointments", iconName: "Calendar" },
      { id: "customers", label: "Patient Records", iconName: "Users" },
      { id: "reports", label: "Medical Reports", iconName: "FileText" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  pharmacy: {
    id: "pharmacy",
    label: "Pharmacy",
    emoji: "💊",
    themeColor: "red",
    textColor: "text-red-400",
    glassTheme: "rgba(239, 68, 68, 0.15)",
    catalogLabel: "Medicine Batches",
    ordersLabel: "Prescription Sales",
    customersLabel: "Patients",
    heroTitle: "Medication Fulfillment Deck",
    heroSubtitle: "Process digital prescription uploads, review dispensary queue stages, and alert batch expiries.",
    onboarding: ["Connect WhatsApp", "Upload Medicine List", "Define RX Verify Rules", "Delivery Sync"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Order Messages", iconName: "MessageSquare" },
      { id: "catalog", label: "Medicine Stock", iconName: "Package" },
      { id: "prescriptions", label: "RX Verification", iconName: "FileText" },
      { id: "orders", label: "Dispensary Queue", iconName: "Clock" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  salon: {
    id: "salon",
    label: "Salon & Spa",
    emoji: "💇",
    themeColor: "pink",
    textColor: "text-pink-400",
    glassTheme: "rgba(236, 72, 153, 0.15)",
    catalogLabel: "Salon Services",
    ordersLabel: "Appointments",
    customersLabel: "Clients",
    heroTitle: "Beauty & Spa Console",
    heroSubtitle: "Manage stylist rosters, package deals, appointment calendars, and automation follow-ups.",
    onboarding: ["Connect WhatsApp", "Add Stylist Profiles", "List Services & Combos", "Setup Slots"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Booking Messages", iconName: "MessageSquare" },
      { id: "doctors", label: "Stylists Panel", iconName: "User" },
      { id: "catalog", label: "Treatment Catalog", iconName: "Package" },
      { id: "orders", label: "Appointments Board", iconName: "Calendar" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  fashion: {
    id: "fashion",
    label: "Fashion Boutique",
    emoji: "👗",
    themeColor: "violet",
    textColor: "text-violet-400",
    glassTheme: "rgba(139, 92, 246, 0.15)",
    catalogLabel: "Apparel catalog",
    ordersLabel: "Purchases",
    customersLabel: "Subscribers",
    heroTitle: "Boutique Styling Deck",
    heroSubtitle: "Release lookbooks, manage catalog sizes, and recovery abandoned carts via WhatsApp templates.",
    onboarding: ["Connect WhatsApp", "Import Apparel SKUs", "Upload Lookbooks", "Set Size Charts"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Customer Chats", iconName: "MessageSquare" },
      { id: "catalog", label: "Apparel Catalog", iconName: "Package" },
      { id: "collections", label: "Lookbooks", iconName: "Sliders" },
      { id: "orders", label: "Orders Registry", iconName: "ShoppingCart" },
      { id: "campaigns", label: "Style Broadcasts", iconName: "Megaphone" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  education: {
    id: "education",
    label: "Education & Academy",
    emoji: "🎓",
    themeColor: "purple",
    textColor: "text-purple-400",
    glassTheme: "rgba(168, 85, 247, 0.15)",
    catalogLabel: "Course Outlines",
    ordersLabel: "Enrollments",
    customersLabel: "Students",
    heroTitle: "Academy Learning Console",
    heroSubtitle: "Coordinate batch times, manage student enrollments, and automate study guide delivery.",
    onboarding: ["Connect WhatsApp", "Create Course Syllabus", "Add Instructors", "Define Batch Timing"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Student Chats", iconName: "MessageSquare" },
      { id: "catalog", label: "Course Syllabus", iconName: "BookOpen" },
      { id: "orders", label: "Enrollments Board", iconName: "ShoppingCart" },
      { id: "batches", label: "Batch Timings", iconName: "Calendar" },
      { id: "customers", label: "Students CRM", iconName: "Users" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
  services: {
    id: "services",
    label: "Professional Services",
    emoji: "💼",
    themeColor: "indigo",
    textColor: "text-indigo-400",
    glassTheme: "rgba(99, 102, 241, 0.15)",
    catalogLabel: "Consulting Packs",
    ordersLabel: "Consultations",
    customersLabel: "Clients",
    heroTitle: "Agency Console Dashboard",
    heroSubtitle: "Track hourly billing ledgers, manage client documents, and sync booking calendars.",
    onboarding: ["Connect WhatsApp", "Create Client Lists", "Sync Google Calendar", "Billing Templates"],
    tabs: [
      { id: "overview", label: "Overview", iconName: "LayoutDashboard" },
      { id: "chats", label: "Client Inboxes", iconName: "MessageSquare" },
      { id: "catalog", label: "Service Packages", iconName: "Package" },
      { id: "orders", label: "Bookings Ledger", iconName: "Calendar" },
      { id: "customers", label: "Clients Directory", iconName: "Users" },
      { id: "billing", label: "Invoices Log", iconName: "FileText" },
      { id: "settings", label: "Settings", iconName: "Settings" },
    ],
  },
};
